#!/bin/bash
set -euo pipefail

docker.test() {
    local name=mesa
    docker rm -f $name || true
    # docker rmi $name || true
    docker build . -t $name
    docker run --privileged -dt \
        -v /dev/dri/:/dev/dri/ \
        -v $HOME:$HOME \
        -p 8082:8080 -p 5902:5900 \
        --name $name \
        $name
}

firefox.install() {
    sudo apt-get install fonts-wqy-zenhei wget

    sudo install -d -m 0755 /etc/apt/keyrings
    wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O-  \
        | sudo tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null
    (gpg -n -q --import --import-options import-show /etc/apt/keyrings/packages.mozilla.org.asc || true) \
        | awk '/pub/{getline; gsub(/^ +| +$/,""); if($0 == "35BAA0B33E9EB396F59CA838C0BA5CE6DC6315A3") print "\nThe key fingerprint matches ("$0").\n"; else print "\nVerification failed: the fingerprint ("$0") does not match the expected one.\n"}'
    echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" \
        | sudo tee -a /etc/apt/sources.list.d/mozilla.list > /dev/null
    echo '
Package: *
Pin: origin packages.mozilla.org
Pin-Priority: 1000' \
        | sudo tee /etc/apt/preferences.d/mozilla
    sudo apt-get update && sudo apt-get install -y firefox
}

docker.start() {
    dbus-daemon --session --nofork --nopidfile --nosyslog --print-address > ~/tmp/dbus.addr.txt &
    sleep 1
    export DBUS_SESSION_BUS_ADDRESS=`cat ~/tmp/dbus.addr.txt`
    labwc -C /etc/xdg/labwc/ --debug
}

help() { echo "run, the minimalist's task runner - https://github.com/simpzan/run"; }
.tasks() { compgen -A function | grep -v "^\."; }
${@:-.tasks}
